// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hive.proto

package com.treasuremountain.datalake.dlapiservice.service.grpc;

public interface hiveSearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hiveSearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sql = 1;</code>
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 1;</code>
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>string extJsonString = 2;</code>
   */
  java.lang.String getExtJsonString();
  /**
   * <code>string extJsonString = 2;</code>
   */
  com.google.protobuf.ByteString
      getExtJsonStringBytes();
}
