// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hive.proto

package com.treasuremountain.datalake.dlapiservice.service.grpc;

public interface hiveSearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hiveSearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataJson = 1;</code>
   */
  java.lang.String getDataJson();
  /**
   * <code>string dataJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataJsonBytes();

  /**
   * <code>bool isError = 2;</code>
   */
  boolean getIsError();

  /**
   * <code>string errorMessage = 3;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
