// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hive.proto

package com.treasuremountain.datalake.dlapiservice.service.grpc;

/**
 * Protobuf type {@code hiveSearchRequest}
 */
public  final class hiveSearchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hiveSearchRequest)
    hiveSearchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use hiveSearchRequest.newBuilder() to construct.
  private hiveSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private hiveSearchRequest() {
    sql_ = "";
    extJsonString_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private hiveSearchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sql_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            extJsonString_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.class, com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.Builder.class);
  }

  public static final int SQL_FIELD_NUMBER = 1;
  private volatile java.lang.Object sql_;
  /**
   * <code>string sql = 1;</code>
   */
  public java.lang.String getSql() {
    java.lang.Object ref = sql_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sql_ = s;
      return s;
    }
  }
  /**
   * <code>string sql = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSqlBytes() {
    java.lang.Object ref = sql_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sql_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTJSONSTRING_FIELD_NUMBER = 2;
  private volatile java.lang.Object extJsonString_;
  /**
   * <code>string extJsonString = 2;</code>
   */
  public java.lang.String getExtJsonString() {
    java.lang.Object ref = extJsonString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extJsonString_ = s;
      return s;
    }
  }
  /**
   * <code>string extJsonString = 2;</code>
   */
  public com.google.protobuf.ByteString
      getExtJsonStringBytes() {
    java.lang.Object ref = extJsonString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extJsonString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSqlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sql_);
    }
    if (!getExtJsonStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extJsonString_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSqlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sql_);
    }
    if (!getExtJsonStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extJsonString_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest)) {
      return super.equals(obj);
    }
    com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest other = (com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest) obj;

    if (!getSql()
        .equals(other.getSql())) return false;
    if (!getExtJsonString()
        .equals(other.getExtJsonString())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SQL_FIELD_NUMBER;
    hash = (53 * hash) + getSql().hashCode();
    hash = (37 * hash) + EXTJSONSTRING_FIELD_NUMBER;
    hash = (53 * hash) + getExtJsonString().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hiveSearchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hiveSearchRequest)
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.class, com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.Builder.class);
    }

    // Construct using com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sql_ = "";

      extJsonString_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchRequest_descriptor;
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest getDefaultInstanceForType() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest build() {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest buildPartial() {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest result = new com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest(this);
      result.sql_ = sql_;
      result.extJsonString_ = extJsonString_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest) {
        return mergeFrom((com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest other) {
      if (other == com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest.getDefaultInstance()) return this;
      if (!other.getSql().isEmpty()) {
        sql_ = other.sql_;
        onChanged();
      }
      if (!other.getExtJsonString().isEmpty()) {
        extJsonString_ = other.extJsonString_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sql_ = "";
    /**
     * <code>string sql = 1;</code>
     */
    public java.lang.String getSql() {
      java.lang.Object ref = sql_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sql_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
      java.lang.Object ref = sql_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql = 1;</code>
     */
    public Builder setSql(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sql_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 1;</code>
     */
    public Builder clearSql() {
      
      sql_ = getDefaultInstance().getSql();
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 1;</code>
     */
    public Builder setSqlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sql_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extJsonString_ = "";
    /**
     * <code>string extJsonString = 2;</code>
     */
    public java.lang.String getExtJsonString() {
      java.lang.Object ref = extJsonString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extJsonString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extJsonString = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExtJsonStringBytes() {
      java.lang.Object ref = extJsonString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extJsonString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extJsonString = 2;</code>
     */
    public Builder setExtJsonString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extJsonString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extJsonString = 2;</code>
     */
    public Builder clearExtJsonString() {
      
      extJsonString_ = getDefaultInstance().getExtJsonString();
      onChanged();
      return this;
    }
    /**
     * <code>string extJsonString = 2;</code>
     */
    public Builder setExtJsonStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extJsonString_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hiveSearchRequest)
  }

  // @@protoc_insertion_point(class_scope:hiveSearchRequest)
  private static final com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest();
  }

  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<hiveSearchRequest>
      PARSER = new com.google.protobuf.AbstractParser<hiveSearchRequest>() {
    @java.lang.Override
    public hiveSearchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new hiveSearchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<hiveSearchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<hiveSearchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

