// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hive.proto

package com.treasuremountain.datalake.dlapiservice.service.grpc;

/**
 * Protobuf type {@code hiveSearchResponse}
 */
public  final class hiveSearchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hiveSearchResponse)
    hiveSearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use hiveSearchResponse.newBuilder() to construct.
  private hiveSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private hiveSearchResponse() {
    dataJson_ = "";
    errorMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private hiveSearchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dataJson_ = s;
            break;
          }
          case 16: {

            isError_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.class, com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.Builder.class);
  }

  public static final int DATAJSON_FIELD_NUMBER = 1;
  private volatile java.lang.Object dataJson_;
  /**
   * <code>string dataJson = 1;</code>
   */
  public java.lang.String getDataJson() {
    java.lang.Object ref = dataJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataJson_ = s;
      return s;
    }
  }
  /**
   * <code>string dataJson = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDataJsonBytes() {
    java.lang.Object ref = dataJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISERROR_FIELD_NUMBER = 2;
  private boolean isError_;
  /**
   * <code>bool isError = 2;</code>
   */
  public boolean getIsError() {
    return isError_;
  }

  public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string errorMessage = 3;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string errorMessage = 3;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDataJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataJson_);
    }
    if (isError_ != false) {
      output.writeBool(2, isError_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDataJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataJson_);
    }
    if (isError_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isError_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse)) {
      return super.equals(obj);
    }
    com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse other = (com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse) obj;

    if (!getDataJson()
        .equals(other.getDataJson())) return false;
    if (getIsError()
        != other.getIsError()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATAJSON_FIELD_NUMBER;
    hash = (53 * hash) + getDataJson().hashCode();
    hash = (37 * hash) + ISERROR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsError());
    hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hiveSearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hiveSearchResponse)
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.class, com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.Builder.class);
    }

    // Construct using com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataJson_ = "";

      isError_ = false;

      errorMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveGrpc.internal_static_hiveSearchResponse_descriptor;
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse getDefaultInstanceForType() {
      return com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse build() {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse buildPartial() {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse result = new com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse(this);
      result.dataJson_ = dataJson_;
      result.isError_ = isError_;
      result.errorMessage_ = errorMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse) {
        return mergeFrom((com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse other) {
      if (other == com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse.getDefaultInstance()) return this;
      if (!other.getDataJson().isEmpty()) {
        dataJson_ = other.dataJson_;
        onChanged();
      }
      if (other.getIsError() != false) {
        setIsError(other.getIsError());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dataJson_ = "";
    /**
     * <code>string dataJson = 1;</code>
     */
    public java.lang.String getDataJson() {
      java.lang.Object ref = dataJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataJson = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataJsonBytes() {
      java.lang.Object ref = dataJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataJson = 1;</code>
     */
    public Builder setDataJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataJson = 1;</code>
     */
    public Builder clearDataJson() {
      
      dataJson_ = getDefaultInstance().getDataJson();
      onChanged();
      return this;
    }
    /**
     * <code>string dataJson = 1;</code>
     */
    public Builder setDataJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataJson_ = value;
      onChanged();
      return this;
    }

    private boolean isError_ ;
    /**
     * <code>bool isError = 2;</code>
     */
    public boolean getIsError() {
      return isError_;
    }
    /**
     * <code>bool isError = 2;</code>
     */
    public Builder setIsError(boolean value) {
      
      isError_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isError = 2;</code>
     */
    public Builder clearIsError() {
      
      isError_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string errorMessage = 3;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errorMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorMessage = 3;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 3;</code>
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 3;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hiveSearchResponse)
  }

  // @@protoc_insertion_point(class_scope:hiveSearchResponse)
  private static final com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse();
  }

  public static com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<hiveSearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<hiveSearchResponse>() {
    @java.lang.Override
    public hiveSearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new hiveSearchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<hiveSearchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<hiveSearchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.treasuremountain.datalake.dlapiservice.service.grpc.hiveSearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

